# -*- coding: utf-8 -*-
"""kmeanpandey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZ3U4wpHWFKOSgI9QEio7EsjX_GXIrcu
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

st.title("🌸 Iris Flower Clustering using K-Means")

# Load Dataset
iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Keep only petal length and petal width
df = df[['petal length (cm)', 'petal width (cm)']]

st.subheader("Dataset")
st.dataframe(df.head())

# Scale the data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

# Select number of clusters
k = st.slider("Select Number of Clusters (K)", 2, 10, 3)

# Apply KMeans
km = KMeans(n_clusters=k, random_state=0)
clusters = km.fit_predict(scaled_data)

df["Cluster"] = clusters

# Cluster Plot
st.subheader("Cluster Visualization")

fig, ax = plt.subplots()

ax.scatter(
    df['petal length (cm)'],
    df['petal width (cm)'],
    c=df['Cluster'],
    cmap='viridis'
)

ax.scatter(
    km.cluster_centers_[:, 0],
    km.cluster_centers_[:, 1],
    color='red',
    marker='*',
    s=250,
    label='Centroids'
)

ax.set_xlabel("Petal Length")
ax.set_ylabel("Petal Width")
ax.legend()

st.pyplot(fig)

# Elbow Method
st.subheader("Elbow Method")

sse = []

for i in range(1, 11):
    model = KMeans(n_clusters=i, random_state=0)
    model.fit(scaled_data)
    sse.append(model.inertia_)

fig2, ax2 = plt.subplots()

ax2.plot(range(1, 11), sse, marker='o')
ax2.set_xlabel("Number of Clusters (K)")
ax2.set_ylabel("SSE")
ax2.set_title("Elbow Plot")

st.pyplot(fig2)

st.success("Optimal value of K from the elbow plot is approximately 3.")


import streamlit as st

st.sidebar.title("👨‍💻 Developer")

st.sidebar.write("**Name:** Richeek Pandey")

st.sidebar.markdown("[🔗 LinkedIn](https://www.linkedin.com/in/YOUR-LINKEDIN-USERNAME/)")

st.sidebar.markdown("[💻 GitHub](https://github.com/YOUR-GITHUB-USERNAME)")
